defaults:
  - settings: sandstorm

hydra:
  run:
    dir: ./hydra_train/${now:%Y-%m-%d_%H-%M-%S}_${hydra_name}
  sweep:
    dir: ./hydra_train/${now:%Y-%m-%d_%H-%M-%S}_${hydra_name}
    subdir: ${hydra.job.num}
  job:
    chdir: True

train:
  epoch_num: 800
  iterations: 1
  latent_dim: 128
  learning_rate: 0.001
  batch_size: 1248
  save_dir: ./saved_model

model_name: sandstorm

data:
  input_csv: /home/nanoribo/NGSprocessing/CELL_IVT/feature/mRNA_halflife_highquaset_withfeatures.csv
